### ISSUE TITLE
Error while running sac.py

### ISSUE THREAD

**Issue by ShahRutav** [ShahRutav/torchrl_examples#1]
The error is in the recorder used by the code

```
Traceback (most recent call last):
  File "sac.py", line 610, in <module>
    main()
  File "sac.py", line 435, in main
    td_record = recorder(None)
  File "/home/rutavms/miniconda3/envs/rlhive/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/rutavms/research/robohive/latest/rl/torchrl/trainers/trainers.py", line 1145, in __call__
    td_record = self.recorder.rollout(
  File "/home/rutavms/research/robohive/latest/rl/torchrl/envs/common.py", line 606, in rollout
    tensordict = self.step(tensordict)
  File "/home/rutavms/research/robohive/latest/rl/torchrl/envs/common.py", line 341, in step
    tensordict_out = self._step(tensordict)
  File "/home/rutavms/research/robohive/latest/rl/torchrl/envs/transforms/transforms.py", line 446, in _step
    tensordict_out = self.base_env._step(tensordict_in)
  File "/home/rutavms/research/robohive/latest/rlhive/rlhive/rl_envs.py", line 155, in _step
    td = super()._step(td)
  File "/home/rutavms/research/robohive/latest/rl/torchrl/envs/gym_like.py", line 183, in _step
    self._env.step(action_np)
  File "/home/rutavms/miniconda3/envs/rlhive/lib/python3.8/site-packages/gym/wrappers/time_limit.py", line 15, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/rutavms/miniconda3/envs/rlhive/lib/python3.8/site-packages/mj_envs/envs/env_base.py", line 188, in step
    self.last_ctrl = self.robot.step(ctrl_desired=a,
  File "/home/rutavms/miniconda3/envs/rlhive/lib/python3.8/site-packages/mj_envs/robot/robot.py", line 666, in step
    ctrl_feasible = self.process_actuator(controls=ctrl_desired, step_duration=step_duration,\
  File "/home/rutavms/miniconda3/envs/rlhive/lib/python3.8/site-packages/mj_envs/robot/robot.py", line 617, in process_actuator
    control = controls[in_id]
IndexError: index 2 is out of bounds for axis 0 with size 2

```

**Comment by ShahRutav** [comment]
[This](915baaf5cd2fbc45bd6e77fb6ef08988ccb6d3e3) issue has been resolved by simply flattening the `r3m_vec`.
