### ISSUE TITLE
Error in make_transformed_env

### ISSUE THREAD

**Issue by ShahRutav** [ShahRutav/torchrl_examples#2]
While trying to use multiple transforms, I ran into an error. This is probably due to `CatTensors`, removing that particular transform resolves the error. 
Error: 
```
Traceback (most recent call last):
  File "test_transforms.py", line 42, in <module>
    td = env.reset()
  File "/home/rutavms/research/robohive/latest/rl/torchrl/envs/common.py", line 431, in reset
    tensordict_reset = self._reset(tensordict, **kwargs)
  File "/home/rutavms/research/robohive/latest/rl/torchrl/envs/transforms/transforms.py", line 470, in _reset
    out_tensordict = self.transform(out_tensordict)
  File "/home/rutavms/miniconda3/envs/rlhive/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/rutavms/research/robohive/latest/rl/torchrl/envs/transforms/r3m.py", line 134, in new_fun
    return fun(self, *args, **kwargs)
  File "/home/rutavms/research/robohive/latest/rl/torchrl/envs/transforms/transforms.py", line 638, in forward
    tensordict = t(tensordict)
  File "/home/rutavms/miniconda3/envs/rlhive/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/rutavms/research/robohive/latest/rl/torchrl/envs/transforms/transforms.py", line 145, in forward
    tensordict = self._call(tensordict)
  File "/home/rutavms/research/robohive/latest/rl/torchrl/envs/transforms/transforms.py", line 1811, in _call
    out_tensor = torch.cat(values, dim=self.dim)
RuntimeError: Tensors must have same number of dimensions: got 1 and 2
```

To reproduce the error [run](https://github.com/ShahRutav/torchrl_examples/blob/robohive_sac_r3m/sac_mujoco/test_transforms.py): `sim_backend=MUJOCO MUJOCO_GL=egl python test_transforms.py`

**Comment by vmoens** [comment]
What does the observation spec contain?

**Comment by ShahRutav** [comment]
I think the issue is this: 
```
base_env  = RoboHiveEnv("visual_franka_slide_random-v3", device=torch.device('cuda:0'))
env = TransformedEnv(env, R3MTransform('resnet50', in_keys=["pixels"], download=True)
```
This environment returns a `r3m_vec` of dimension [2, 2048] but `observation` of dimension [12]. This creates the issue while concatenating the two observations

**Comment by ShahRutav** [comment]
There are two cameras that is why the output of `r3m_vec` is [2, 2048]. Is there a transform to linearize this?

**Comment by ShahRutav** [comment]
[This](93ec43e634a243b6d2ef8c22b2cb5bb4c6078fc9) has been fixed by add FlattenObservation after R3MTransform
